sudo: required
services:
  - docker

before_install:
  - docker build -t kyawlin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kyawlin/react-test npm test

after_success:
  - docker build -t kyawlin/complex-client ./client
  - docker build -t kyawlin/complex-nginx ./nginx
  - docker build -t kyawlin/complex-server ./server
  - docker build -t kyawlin/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kyawlin/complex-client
  - docker push kyawlin/complex-nginx
  - docker push kyawlin/complex-server
  - docker push kyawlin/complex-worker